<?php

namespace GSB\VisiteurBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * FraisForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisForfaitRepository extends \Doctrine\ORM\EntityRepository
{
    function listerFraisForfait()
    {
    $qb = $this->_em->createQueryBuilder('v');
    
    $qb->select('v')
    ->from('GSBVisiteurBundle:FraisForfait', 'v');
    
    $req = $qb->getQuery()->getResult();
    
    return $req;
    
    }
    
    function modifierFraisForfait($id,$montant)
    {
    $qb = $this->_em->createQueryBuilder('v');
    
    $qb->update('GSBVisiteurBundle:FraisForfait','v')
    ->set('v.montant',$montant)
    ->where ('v.id = :val')
    ->setParameter('val',$id);
    
    $query = $qb->getQuery();
            
    $resultat = $query->getResult();
    
    return $resultat;
    }
    
}
