<?php

namespace GSB\VisiteurBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;


/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends \Doctrine\ORM\EntityRepository
    {
    
    function listerVisiteur($id)
    {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('v')
    ->from('GSBVisiteurBundle:Visiteur', 'v')
    ->where ($qb->expr()->eq('v.id',':val'))
    ->setParameter('val',$id);
    $query = $qb->getQuery();
    $resultat = $query->getResult();
    return $resultat;
    }
    
    
}
